module: AMCoreAudio
author: 9Labs
github_url: https://github.com/rnine/AMCoreAudio

theme: fullwidth
clean: true

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

swift_build_tool: spm
