name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install NullAudio.driver
      run: sudo unzip Tests/Extras/NullAudio.driver.zip -d /Library/Audio/Plug-Ins/HAL
    - name: Restart Core Audio
      run: sudo launchctl kill KILL system/com.apple.audio.coreaudiod      
    - name: Check Null Audio Device is present
      run: system_profiler SPAudioDataType | grep -c "Null Audio Device"
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
